default_template = "/_templates/index.html"

[catalogs]
default_card_template = "/_templates/link.html"

[[catalogs.entries]]
title = "Projects"
path = "/projects"
directory = "/projects"
card_template = "/_templates/article-card.html"


[meta]
title_template = "%title% | larana.tech"
description_template = "%description%"
keywords_template = "%keywords%, larana, larana.tech"
fallback_title = "Fallback title"
fallback_description = "Fallback description"
fallback_keywords = "Fallback keywords"


[lazyness]
images = true
first_image = false
