default_template = "/_templates/index.html"
hotreload = false
debug = true


[catalogs]
default_catalog_template = "/_templates/index.html"
default_card_template = "/_templates/link.html"

[[catalogs.entries]]
title = "Projects"
path = "/projects"
directory = "/projects"
card_template = "/_templates/article-card.html"


[meta]

[[meta.tags]]
key = "title"
template = "%s | larana.tech"
fallback = "No title"
tag = "title"

[[meta.tags]]
key = "keywords"
template = "%s, larana, larana.tech"
fallback = "No keywords"
tag = "meta"

[[meta.tags]]
key = "description"
template = "%s"
fallback = "No description"
tag = "meta"

[[meta.tags]]
key = "date"
template = "%s"
fallback = ""
tag = "meta"


[lazyness]
images = true
first_image = false

